name: 'Mosquitto MQTT Broker in GitHub Actions'
description: 'Start a Mosquitto message broker as Docker container'

branding:
  icon: 'message-square'
  color: 'red'

inputs:
  version:
    description: 'Mosquitto version to use'
    required: false
    default: 'latest'
  ports:
    description: 'Port mappings in a [host]:[container] format, delimited by spaces (example: "1883:1883 8883:8883")'
    required: false
    default: '1883:1883'
  certificates:
    description: 'Absolute path to a directory containing certificate files which can be referenced in the config (the folder is mounted under `/mosquitto-certs`)'
    required: false
    default: ''
  config:
    description: 'Absolute path to the mosquitto.conf configuration file to use'
    required: false
    default: ''
  password-file:
    description: 'Absolute path to the mosquitto.passwd password file to use'
    required: false
    default: ''
  data:
    description: 'Absolute path to a host directory into which /mosquitto/data in the container will be mounted.'
    required: false
    default: ''
  log:
    description: 'Absolute path to a host directory into which /mosquitto/log in the container will be mounted.'
    required: false
    default: ''
  extra-args:
    description: 'Arbitrary extra arguments passed to "docker run" command before the container name'
  container-name:
    description: 'The name of the spawned Docker container (can be used as hostname when accessed from other containers)'
    required: false
    default: 'mosquitto'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
    - ${{ inputs.ports }}
    - ${{ inputs.certificates }}
    - ${{ inputs.config }}
    - ${{ inputs.password-file }}
    - ${{ inputs.data }}
    - ${{ inputs.log }}
    - ${{ inputs.exrta-args }}
    - ${{ inputs.container-name }}
