name: Test Action

on:
  push:
    branches:
      - master
      - ci
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-broker:
    name: Test Mosquitto Docker image version [${{ matrix.version }}]

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          # - { version: '1.5' }
          # - { version: '1.6' }
          # - { version: '2.0' }
          # - { version: 'latest'}
          # - { version: "latest", data: '/home/runner/mosquitto-data'}
          # - { version: "latest", log: '/home/runner/mosquitto-log'}
          # - { version: "latest", EXTRA_ARGS: '--volume /home/runner/mosquitto-config:/mosquitto/config'}
          - { version: "latest",
              data: '/home/runner/mosquitto-data',
              log: '/home/runner/mosquitto-log',
              extra-args: '--volume /home/runner/mosquitto-config:/mosquitto/config'
          }

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start Mosquitto
        uses: ./
        with:
          data: ${{ matrix.data }}
          log: ${{ matrix.log }}
          extra-args: ${{ matrix.extra-args }}
          version: ${{ matrix.version }}

      - name: Check data directory
        if: matrix.data != ''
        run: |
          ls -l /home/runner
          echo 3
          ls /home/runner/mosquitto-data
          echo 4
          ls /home/runner/mosquitto-log
          echo 5
          ls /home/runner/mosquitto-config
          echo 6

      - name: Check log directory
        if: matrix.log != ''
        run: |
          echo "LOG_DIR: $LOG_DIR"
          ls $LOG_DIR

      - name: Check extra args via config directory
        if: matrix.extra-args != ''
        run: |
          echo "CONFIG_DIR: $CONFIG_DIR"
          ls $$CONFIG_DIR
          
