name: Test Action

on:
  push:
    branches:
      - master
      - dev
      - 'feature/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
#  test-broker:
#    name: Test Mosquitto Docker image version [${{ matrix.version }}]
#
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        version: ['1.5', '1.6', '2.0', 'latest']
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Start Mosquitto
#        uses: ./
#        with:
#          version: ${{ matrix.version }}

  test-log:
    name: Test mounting of logging directory with 'log' input [${{ matrix.version }}]

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ['latest']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start Mosquitto
        uses: ./
        with:
          version: ${{ matrix.version }}
          config: ${{ github.workspace }}/test-data/mosquitto-log.conf
          log: ${{ github.workspace }}/test-data/bind-mounts/mosquitto/log
          data: ${{ github.workspace }}/test-data/bind-mounts/mosquitto/data

      - name: Install mosquitto client
        run: |
          sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa
          sudo apt-get update
          sudo apt-get install mosquitto-clients

      - name: Wait for Mosquitto
        uses: iFaxity/wait-on-action@v1.1.0
        with:
          resource: tcp:localhost:1883
          timeout: 5000

      - name: Connect to Mosquitto
        continue-on-error: true
        run: |
          echo 1 pub clear
          mosquitto_pub -h localhost -p 1883 -t foo -m '{"bla":1}'
          echo 2 sub clear
          mosquitto_sub -h localhost -p 1883 -t foo -E
          echo 3

      - name: Check log file
        run: |
          which docker
          docker --version
          docker ps
          docker logs mosquitto
#          echo "Log directory: <${{ github.workspace }}/test-data/bind-mounts/mosquitto/log>"
#          echo 1
#          ls -l ${{ github.workspace }}/test-data/bind-mounts/mosquitto
#          echo 2
#          ls -l ${{ github.workspace }}/test-data/bind-mounts/mosquitto/log
#          echo 3
#          ls -l ${{ github.workspace }}/test-data/bind-mounts/mosquitto/log/mosquitto.log | true
#          echo 4
#          cat ${{ github.workspace }}/test-data/bind-mounts/mosquitto/log/mosquitto.log | true
#          echo 5
#          ls -l ${{ github.workspace }}/test-data/bind-mounts/mosquitto/data | true
#          echo 7
#          docker ps | true
#          echo 8

