name: Test Action

on:
  push:
    branches:
      - master
      - ci
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-broker:
    name: Test Mosquitto Docker image version [${{ matrix.version }}]

    runs-on: ubuntu-latest

    env:
      DATA_DIR: 'mosquitto-data'
      LOG_DIR: '$HOME/mosquitto-log'
      CONFIG_DIR: '$HOME/mosquitto-config'
      EXTRA_ARGS: '--volume $config-dir:/mosquitto/config'

    strategy:
      matrix:
        include:
          # - { version: '1.5' }
          # - { version: '1.6' }
          # - { version: '2.0' }
          # - { version: 'latest'}
          - { version: "latest", data: '$HOME/$DATA_DIR'}
          # - { version: "latest", log: '$LOG_DIR'}
          # - { version: "latest", EXTRA_ARGS: '$EXTRA_ARGS'}
          # - { version: "latest", data: '$DATA_DIR', log: '$LOG_DIR', extra-args: '$EXTRA_ARGS'}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start Mosquitto
        uses: ./
        with:
          version: ${{ matrix.version }}

      - name: Check data directory
        if: matrix.data != ''
        run: |
          echo "HOME: $HOME"
          echo $HOME
          ls $HOME
          echo 1
          ls /home/runner
          echo 2
          echo "DATA_DIR: $DATA_DIR" 
          echo 3
          echo "HOME/DATA_DIR: $HOME/$DATA_DIR" 
          echo 4
          ls $HOME/$DATA_DIR

      - name: Check log directory
        if: matrix.log != ''
        run: |
          echo "LOG_DIR: $LOG_DIR"
          ls $LOG_DIR

      - name: Check extra args via config directory
        if: matrix.extra-args != ''
        run: |
          echo "CONFIG_DIR: $CONFIG_DIR"
          ls $$CONFIG_DIR
          
