name: Test Action

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-broker:
    name: Test Mosquitto Docker image version [${{ matrix.version }}]

    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [
          # '1.5', '1.6', '2.0',
          'latest'
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start Mosquitto
        uses: ./
        with:
          version: ${{ matrix.version }}
